### ISSUE TITLE
Corrigir legenda do grafo de requisitos (seta de requisito fraco não é pontilhada)

### ISSUE THREAD

**Issue by tprei** [Projeto-USPY/uspy-frontend#19]
![image](https://user-images.githubusercontent.com/37089330/129430416-4a562532-6c33-48ac-8ec6-6acef0fe4e67.png)

**Comment by lucasturci** [comment]
O requisito forte deveria ser representado por uma seta mais espessa, e o fraco por essa seta da imagem
