### ISSUE TITLE
Botão para a página de comentários no histórico interativo

### ISSUE THREAD

**Issue by tprei** [Projeto-USPY/uspy-frontend#48]

**Comment by lucasturci** [comment]
Adicionei botão na versão mobile e dentro do modal de avaliação:

![image](https://user-images.githubusercontent.com/17186683/151619244-2deb4992-b46a-4de1-ba85-0762ca19579d.png)
![image](https://user-images.githubusercontent.com/17186683/151619351-5cf91d75-7866-43d1-b464-53a4efe152d0.png)

Na versão desktop não encontrei uma boa forma de incluir, porque acredito que outra coluna na tabela deixa ela muito poluida. O link ainda pode ser acessado a partir do modal, então por enquanto fica sendo essa a forma de acessar os reviews
