### ISSUE TITLE
Melhorar grafo de requisitos

### ISSUE THREAD

**Issue by tprei** [Projeto-USPY/uspy-frontend#8]
- [x] Destacar o nó central utilizando uma borda mais acentuada
- [x] Diferenciar requisitos fortes de fracos usando tipo de aresta (completa ou tracejada)
- [x] Tooltip apenas com o nome da disciplina no nó central
- [x] Criar legenda pra aresta fina e grossa

**Comment by lucasturci** [comment]
@tprei 
Na task 2, preciso que o endpoint de `/api/subject/relations` retorne também se a matéria é optativa ou obrigatória
